version: "3"

services:
  frontend:
    # build: ./frontend
    ports:
      - '80:80'
    image: pranjalya/stockviewer_frontend
    depends_on:
      - app

  app:
    container_name: app
    # build:
      # context: ./app
      # dockerfile: Dockerfile
    image: pranjalya/stockviewer_app
    hostname: app
    ports:
      - 8000:8000
    env_file: .env
    command: gunicorn app.wsgi -b 0.0.0.0:8000
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - '6353:6353'
    command: --port 6353