version: "3.7"

services:
  app:
    build: ./app
    command: bash -c "python ./app/manage.py makemigrations && python ./app/manage.py migrate && python manage.py ./app/runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env

  redis:
      image: "redis:alpine"
